### ISSUE TITLE
Cannot import name '_asarray_validated' from 'scipy.linalg.decomp'

### ISSUE THREAD

**Issue by michele-franzan** [ilayn/harold#77] opened 2022-04-12 14:43 UTC
Including harold package leads to the following error when running a script:

```
  File "C:\Users\michele.franzan\AppData\Local\Programs\Python\Python310\lib\site-packages\harold\__init__.py", line 30, in <module>
    from ._classes import *
  File "C:\Users\michele.franzan\AppData\Local\Programs\Python\Python310\lib\site-packages\harold\_classes.py", line 6, in <module>
    from scipy.linalg.decomp import _asarray_validated
ImportError: cannot import name '_asarray_validated' from 'scipy.linalg.decomp' (C:\Users\michele.franzan\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\linalg\decomp.py)
```

I've found out that the _asarray_validated() function is included in scipy._lib._util instead of scipy.linalg.decomp.

**Comment by ilayn** [comment] 2022-04-12 15:19
Thank you @michele-franzan for reporting. I've fixed it in the master branch but didn't make a release yet. If you don't mind, you can clone the directory and use the master branch for this. Sorry for the inconvenience. I'm trying to find some time to make a proper release.

**Comment by ilayn** [comment] 2022-04-12 16:50
Duplicate of #74

**Closed by ilayn** 2022-04-12 16:50 UTC
